### ISSUE TITLE
Manually selected starting points are not well recognized

### ISSUE THREAD

**Issue by Chengmz** [jumphone/Vector#1]
First of all, thank you very much for creating a script that not only recognizes accurately but also runs very fast!
During using, I found that when manually selecting the start point, the point marked by the mouse does not match the displayed point when running the next step. In fact, the script thinks that the marked point is far to the upper left than I select.

Looking forward to receiving your reply

**Comment by jumphone** [comment]
1. The point selection function of VECTOR is based on the "fhs" function of the "gatepoints" package. You can directly test the "fhs" function. 
2. Please make sure that those selected points are in "the largest connected pixel network" (Please check the original paper of VECTOR).
